name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2  # Certifique-se de usar a versão 2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package  # Compila o projeto e cria o JAR

      - name: Run Tests
        run: mvn test  # Executa os testes

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maven-build
          path: target/*.jar  # Upload do JAR gerado para os artefatos
